export interface BlogArticle {
  slug: string;
  title: string;
  description: string;
  category: string;
  date: string;
  readTime: string;
  author: string;
  tags: string[];
}

export const BLOG_CATEGORIES = [
  "Website",
  "Aplikasi",
  "SEO",
  "Digital Marketing",
  "Tutorial",
  "Tips",
  "Teknologi",
  "Bisnis",
  "UI/UX",
  "AI",
] as const;

export const BLOG_ARTICLES: BlogArticle[] = [
  { slug: "jasa-pembuatan-website-bandung-panduan-lengkap", title: "Jasa Pembuatan Website Bandung: Panduan Lengkap 2025", description: "Panduan lengkap memilih jasa pembuatan website terbaik di Bandung. Tips, harga, dan rekomendasi untuk bisnis Anda.", category: "Website", date: "2025-06-01", readTime: "8 menit", author: "Tim Nufanas", tags: ["jasa website bandung", "web developer", "website bisnis"] },
  { slug: "cara-meningkatkan-seo-website-bisnis-lokal", title: "Cara Meningkatkan SEO Website untuk Bisnis Lokal Bandung", description: "Strategi SEO lokal yang terbukti efektif untuk mendominasi pencarian Google di area Bandung dan Jawa Barat.", category: "SEO", date: "2025-05-28", readTime: "10 menit", author: "Tim Nufanas", tags: ["seo lokal", "google bisnis", "ranking google"] },
  { slug: "website-company-profile-pentingnya-untuk-bisnis", title: "Website Company Profile: Mengapa Penting untuk Bisnis?", description: "Alasan mengapa setiap bisnis perlu memiliki website company profile profesional dan bagaimana cara membuatnya.", category: "Website", date: "2025-05-25", readTime: "6 menit", author: "Tim Nufanas", tags: ["company profile", "website bisnis", "branding"] },
  { slug: "next-js-vs-wordpress-mana-yang-lebih-baik", title: "Next.js vs WordPress: Mana yang Lebih Baik untuk Website Bisnis?", description: "Perbandingan lengkap Next.js dan WordPress dari segi performa, SEO, keamanan, dan biaya maintenance.", category: "Teknologi", date: "2025-05-20", readTime: "12 menit", author: "Tim Nufanas", tags: ["nextjs", "wordpress", "web development"] },
  { slug: "panduan-memilih-domain-website-bisnis", title: "Panduan Memilih Domain untuk Website Bisnis", description: "Tips memilih nama domain yang tepat untuk bisnis Anda. Ekstensi .com, .co.id, atau .id? Simak rekomendasinya.", category: "Tips", date: "2025-05-15", readTime: "5 menit", author: "Tim Nufanas", tags: ["domain", "hosting", "website"] },
  { slug: "optimasi-kecepatan-website-core-web-vitals", title: "Optimasi Kecepatan Website: Panduan Core Web Vitals", description: "Cara mengoptimasi Core Web Vitals website Anda untuk skor Lighthouse 100 dan ranking lebih baik di Google.", category: "SEO", date: "2025-05-10", readTime: "15 menit", author: "Tim Nufanas", tags: ["core web vitals", "lighthouse", "page speed"] },
  { slug: "biaya-pembuatan-aplikasi-mobile-2025", title: "Biaya Pembuatan Aplikasi Mobile 2025: Panduan Lengkap", description: "Berapa biaya membuat aplikasi Android dan iOS? Panduan estimasi harga berdasarkan fitur dan kompleksitas.", category: "Aplikasi", date: "2025-05-05", readTime: "10 menit", author: "Tim Nufanas", tags: ["biaya aplikasi", "android", "ios"] },
  { slug: "flutter-vs-react-native-mana-yang-terbaik", title: "Flutter vs React Native: Mana yang Terbaik untuk Aplikasi Mobile?", description: "Perbandingan Flutter dan React Native untuk pengembangan aplikasi cross-platform. Kelebihan dan kekurangan masing-masing.", category: "Teknologi", date: "2025-04-30", readTime: "12 menit", author: "Tim Nufanas", tags: ["flutter", "react native", "mobile app"] },
  { slug: "cara-membuat-website-toko-online", title: "Cara Membuat Website Toko Online yang Menghasilkan", description: "Step-by-step membuat website e-commerce yang profesional dan siap menghasilkan penjualan untuk bisnis Anda.", category: "Tutorial", date: "2025-04-25", readTime: "15 menit", author: "Tim Nufanas", tags: ["toko online", "ecommerce", "website jualan"] },
  { slug: "apa-itu-seo-dan-manfaatnya-untuk-bisnis", title: "Apa Itu SEO dan Manfaatnya untuk Bisnis Online?", description: "Penjelasan lengkap tentang SEO (Search Engine Optimization) dan bagaimana SEO bisa meningkatkan traffic dan penjualan.", category: "SEO", date: "2025-04-20", readTime: "8 menit", author: "Tim Nufanas", tags: ["seo dasar", "optimasi mesin pencari", "traffic organik"] },
  { slug: "manfaat-website-untuk-umkm", title: "10 Manfaat Website untuk UMKM di Era Digital", description: "Mengapa UMKM wajib punya website? Simak 10 manfaat website yang bisa meningkatkan omset bisnis kecil Anda.", category: "Bisnis", date: "2025-04-15", readTime: "7 menit", author: "Tim Nufanas", tags: ["umkm", "bisnis online", "website murah"] },
  { slug: "jasa-pembuatan-aplikasi-android-bandung", title: "Jasa Pembuatan Aplikasi Android Bandung: Panduan Memilih yang Tepat", description: "Tips memilih vendor pembuatan aplikasi Android di Bandung. Dari harga, portofolio, hingga teknologi yang digunakan.", category: "Aplikasi", date: "2025-04-10", readTime: "9 menit", author: "Tim Nufanas", tags: ["aplikasi android", "software house bandung", "mobile developer"] },
  { slug: "cara-optimasi-google-my-business", title: "Cara Optimasi Google My Business untuk Bisnis Lokal", description: "Langkah-langkah mengoptimasi profil Google Business agar bisnis Anda muncul di pencarian lokal dan Google Maps.", category: "SEO", date: "2025-04-05", readTime: "8 menit", author: "Tim Nufanas", tags: ["google business", "seo lokal", "google maps"] },
  { slug: "perbedaan-website-dan-landing-page", title: "Perbedaan Website dan Landing Page: Mana yang Bisnis Anda Butuhkan?", description: "Memahami perbedaan mendasar antara website dan landing page, serta kapan sebaiknya menggunakan masing-masing.", category: "Tips", date: "2025-03-30", readTime: "6 menit", author: "Tim Nufanas", tags: ["landing page", "website", "conversion"] },
  { slug: "tren-website-2025-yang-wajib-diketahui", title: "10 Tren Website 2025 yang Wajib Diketahui Pebisnis", description: "Tren desain dan teknologi website terbaru di 2025: AI, 3D, micro-interactions, dark mode, dan lainnya.", category: "Teknologi", date: "2025-03-25", readTime: "10 menit", author: "Tim Nufanas", tags: ["tren website", "desain web", "teknologi terbaru"] },
  { slug: "cara-membuat-aplikasi-kasir-untuk-bisnis", title: "Cara Membuat Aplikasi Kasir untuk Bisnis Retail dan F&B", description: "Panduan pembuatan aplikasi POS (Point of Sale) untuk toko, cafe, dan restoran. Fitur, teknologi, dan estimasi biaya.", category: "Aplikasi", date: "2025-03-20", readTime: "11 menit", author: "Tim Nufanas", tags: ["aplikasi kasir", "pos system", "bisnis retail"] },
  { slug: "pentingnya-ssl-untuk-website-bisnis", title: "Pentingnya SSL Certificate untuk Website Bisnis Anda", description: "Mengapa SSL wajib untuk setiap website bisnis. Pengaruhnya terhadap keamanan, SEO, dan kepercayaan pelanggan.", category: "Tips", date: "2025-03-15", readTime: "5 menit", author: "Tim Nufanas", tags: ["ssl", "keamanan website", "https"] },
  { slug: "erp-system-panduan-lengkap-untuk-bisnis", title: "ERP System: Panduan Lengkap untuk Bisnis di Indonesia", description: "Apa itu ERP (Enterprise Resource Planning)? Manfaat, modul, biaya implementasi, dan rekomendasi untuk bisnis menengah.", category: "Bisnis", date: "2025-03-10", readTime: "14 menit", author: "Tim Nufanas", tags: ["erp", "enterprise software", "manajemen bisnis"] },
  { slug: "ui-ux-design-meningkatkan-conversion-rate", title: "UI/UX Design yang Meningkatkan Conversion Rate Website", description: "Prinsip-prinsip UI/UX design yang terbukti meningkatkan conversion rate. Best practice dari website top dunia.", category: "UI/UX", date: "2025-03-05", readTime: "10 menit", author: "Tim Nufanas", tags: ["ui ux", "conversion rate", "desain website"] },
  { slug: "cara-memilih-hosting-terbaik-indonesia", title: "Cara Memilih Hosting Terbaik di Indonesia untuk Website", description: "Perbandingan hosting Indonesia terbaik: shared, VPS, cloud, dan dedicated. Rekomendasi berdasarkan kebutuhan.", category: "Tutorial", date: "2025-02-28", readTime: "9 menit", author: "Tim Nufanas", tags: ["hosting", "web hosting", "cloud hosting"] },
  { slug: "strategi-digital-marketing-untuk-umkm", title: "Strategi Digital Marketing untuk UMKM: Dari Nol Sampai Profit", description: "Panduan digital marketing lengkap untuk UMKM. Mulai dari social media, SEO, Google Ads, hingga email marketing.", category: "Digital Marketing", date: "2025-02-25", readTime: "13 menit", author: "Tim Nufanas", tags: ["digital marketing", "umkm", "marketing online"] },
  { slug: "apa-itu-crm-dan-manfaatnya", title: "Apa Itu CRM dan Manfaatnya untuk Meningkatkan Penjualan?", description: "Customer Relationship Management (CRM) explained: pengertian, manfaat, fitur utama, dan rekomendasi CRM terbaik.", category: "Bisnis", date: "2025-02-20", readTime: "8 menit", author: "Tim Nufanas", tags: ["crm", "customer management", "sales"] },
  { slug: "google-ads-vs-meta-ads-mana-yang-lebih-efektif", title: "Google Ads vs Meta Ads: Mana yang Lebih Efektif untuk Bisnis?", description: "Perbandingan Google Ads dan Meta Ads (Facebook/Instagram). Kapan menggunakan masing-masing dan budget optimalnya.", category: "Digital Marketing", date: "2025-02-15", readTime: "11 menit", author: "Tim Nufanas", tags: ["google ads", "meta ads", "iklan digital"] },
  { slug: "cara-membuat-website-sekolah-yang-informatif", title: "Cara Membuat Website Sekolah yang Informatif dan Modern", description: "Panduan membuat website sekolah dengan fitur PPDB online, e-learning, portal orang tua, dan berita kegiatan.", category: "Tutorial", date: "2025-02-10", readTime: "9 menit", author: "Tim Nufanas", tags: ["website sekolah", "pendidikan", "ppdb online"] },
  { slug: "ai-automation-untuk-bisnis-2025", title: "AI Automation untuk Bisnis: Tren dan Implementasi 2025", description: "Bagaimana AI dan otomasi bisa meningkatkan efisiensi bisnis Anda. Use case nyata dan tools yang bisa digunakan.", category: "AI", date: "2025-02-05", readTime: "12 menit", author: "Tim Nufanas", tags: ["ai automation", "artificial intelligence", "otomasi bisnis"] },
  { slug: "website-klinik-fitur-yang-wajib-ada", title: "Website Klinik: 15 Fitur yang Wajib Ada untuk Menarik Pasien", description: "Fitur-fitur penting yang harus dimiliki website klinik dan rumah sakit untuk meningkatkan jumlah pasien baru.", category: "Website", date: "2025-01-30", readTime: "8 menit", author: "Tim Nufanas", tags: ["website klinik", "kesehatan digital", "appointment online"] },
  { slug: "cara-meningkatkan-traffic-website-organik", title: "15 Cara Meningkatkan Traffic Website secara Organik", description: "Strategi terbukti untuk meningkatkan traffic website tanpa iklan. Content marketing, SEO, dan link building.", category: "SEO", date: "2025-01-25", readTime: "14 menit", author: "Tim Nufanas", tags: ["traffic website", "seo organik", "content marketing"] },
  { slug: "hris-system-manajemen-sdm-modern", title: "HRIS System: Solusi Manajemen SDM Modern untuk Perusahaan", description: "Mengenal HRIS (Human Resource Information System): fitur, manfaat, dan cara implementasi untuk efisiensi HR.", category: "Bisnis", date: "2025-01-20", readTime: "10 menit", author: "Tim Nufanas", tags: ["hris", "human resource", "manajemen sdm"] },
  { slug: "responsive-design-pentingnya-untuk-mobile", title: "Responsive Design: Mengapa Website Harus Mobile-Friendly?", description: "Penjelasan responsive design dan mengapa 70% pengguna internet Indonesia mengakses dari smartphone.", category: "Website", date: "2025-01-15", readTime: "6 menit", author: "Tim Nufanas", tags: ["responsive design", "mobile friendly", "ux mobile"] },
  { slug: "jasa-seo-bandung-apa-yang-didapat", title: "Jasa SEO Bandung: Apa yang Anda Dapatkan dan Berapa Biayanya?", description: "Transparansi layanan SEO: apa saja yang dikerjakan, timeline, dan estimasi biaya jasa SEO di Bandung.", category: "SEO", date: "2025-01-10", readTime: "9 menit", author: "Tim Nufanas", tags: ["jasa seo", "seo bandung", "harga seo"] },
  { slug: "cara-membuat-marketplace-online", title: "Cara Membuat Marketplace Online: Dari Ide Sampai Launch", description: "Step-by-step membangun platform marketplace multi-vendor. Teknologi, fitur MVP, dan strategi go-to-market.", category: "Tutorial", date: "2025-01-05", readTime: "16 menit", author: "Tim Nufanas", tags: ["marketplace", "multi vendor", "platform"] },
  { slug: "website-hotel-meningkatkan-direct-booking", title: "Website Hotel: Strategi Meningkatkan Direct Booking", description: "Bagaimana website hotel yang baik bisa meningkatkan direct booking dan mengurangi ketergantungan pada OTA.", category: "Website", date: "2024-12-30", readTime: "9 menit", author: "Tim Nufanas", tags: ["website hotel", "booking online", "hospitality"] },
  { slug: "kotlin-vs-java-untuk-android-development", title: "Kotlin vs Java untuk Android Development: Mana yang Dipilih?", description: "Perbandingan Kotlin dan Java untuk pengembangan aplikasi Android. Kelebihan Kotlin dan kapan Java masih relevan.", category: "Teknologi", date: "2024-12-25", readTime: "10 menit", author: "Tim Nufanas", tags: ["kotlin", "java", "android development"] },
  { slug: "schema-markup-meningkatkan-ctr-google", title: "Schema Markup: Cara Meningkatkan CTR di Hasil Pencarian Google", description: "Panduan implementasi schema markup untuk rich snippets. FAQ, HowTo, Review, dan LocalBusiness schema.", category: "SEO", date: "2024-12-20", readTime: "11 menit", author: "Tim Nufanas", tags: ["schema markup", "rich snippets", "structured data"] },
  { slug: "saas-development-panduan-membangun-produk", title: "SaaS Development: Panduan Membangun Produk Software as a Service", description: "Langkah-langkah membangun produk SaaS dari ideation, MVP, hingga scaling. Tech stack dan model bisnis.", category: "Teknologi", date: "2024-12-15", readTime: "15 menit", author: "Tim Nufanas", tags: ["saas", "software development", "startup"] },
  { slug: "website-properti-fitur-dan-strategi-seo", title: "Website Properti: Fitur Penting dan Strategi SEO yang Efektif", description: "Cara membuat website properti yang menarik calon pembeli. Fitur listing, peta interaktif, dan SEO properti.", category: "Website", date: "2024-12-10", readTime: "10 menit", author: "Tim Nufanas", tags: ["website properti", "real estate", "listing property"] },
  { slug: "cara-setup-google-analytics-4", title: "Cara Setup Google Analytics 4 untuk Website: Panduan Lengkap", description: "Tutorial step-by-step memasang Google Analytics 4 (GA4). Dari instalasi, event tracking, hingga membaca data.", category: "Tutorial", date: "2024-12-05", readTime: "12 menit", author: "Tim Nufanas", tags: ["google analytics", "ga4", "web analytics"] },
  { slug: "digital-agency-vs-freelancer-mana-yang-dipilih", title: "Digital Agency vs Freelancer: Mana yang Harus Dipilih?", description: "Kelebihan dan kekurangan bekerja dengan digital agency vs freelancer. Tips memilih berdasarkan budget dan kebutuhan.", category: "Tips", date: "2024-12-01", readTime: "7 menit", author: "Tim Nufanas", tags: ["digital agency", "freelancer", "vendor website"] },
  { slug: "chatgpt-untuk-bisnis-use-case-dan-implementasi", title: "ChatGPT untuk Bisnis: Use Case dan Cara Implementasi", description: "Bagaimana memanfaatkan ChatGPT dan AI generatif untuk meningkatkan produktivitas dan customer service bisnis.", category: "AI", date: "2024-11-25", readTime: "11 menit", author: "Tim Nufanas", tags: ["chatgpt", "ai generatif", "produktivitas bisnis"] },
  { slug: "website-cafe-restoran-meningkatkan-pelanggan", title: "Website Cafe & Restoran: Cara Meningkatkan Pelanggan Online", description: "Strategi digital untuk cafe dan restoran: website, menu digital, reservasi online, dan review management.", category: "Website", date: "2024-11-20", readTime: "8 menit", author: "Tim Nufanas", tags: ["website cafe", "website restoran", "digital fnb"] },
  { slug: "local-seo-checklist-bisnis-lokal", title: "Local SEO Checklist: 20 Langkah untuk Bisnis Lokal", description: "Checklist lengkap optimasi SEO lokal untuk mendominasi pencarian Google di kota Anda. Langkah demi langkah.", category: "SEO", date: "2024-11-15", readTime: "13 menit", author: "Tim Nufanas", tags: ["local seo", "seo checklist", "bisnis lokal"] },
  { slug: "aplikasi-inventory-management-panduan", title: "Aplikasi Inventory Management: Panduan untuk Bisnis Retail", description: "Mengenal sistem inventory management digital. Fitur penting, manfaat, dan rekomendasi untuk bisnis retail.", category: "Aplikasi", date: "2024-11-10", readTime: "9 menit", author: "Tim Nufanas", tags: ["inventory management", "stok barang", "aplikasi gudang"] },
  { slug: "cara-optimasi-gambar-website-untuk-seo", title: "Cara Optimasi Gambar Website untuk SEO dan Kecepatan", description: "Teknik optimasi gambar: format WebP/AVIF, lazy loading, responsive images, dan alt text yang efektif.", category: "Tutorial", date: "2024-11-05", readTime: "7 menit", author: "Tim Nufanas", tags: ["optimasi gambar", "image seo", "web performance"] },
  { slug: "mengapa-bisnis-perlu-web-application", title: "Mengapa Bisnis Perlu Web Application? Bukan Sekadar Website", description: "Perbedaan website biasa dan web application. Kapan bisnis Anda butuh custom web app untuk otomasi proses.", category: "Bisnis", date: "2024-11-01", readTime: "8 menit", author: "Tim Nufanas", tags: ["web application", "custom software", "otomasi"] },
  { slug: "geo-optimasi-ai-search-panduan-2025", title: "GEO (Generative Engine Optimization): Panduan Optimasi untuk AI Search", description: "Cara mengoptimasi website agar muncul di Google AI Overview, ChatGPT, Gemini, dan Perplexity.", category: "SEO", date: "2024-10-25", readTime: "14 menit", author: "Tim Nufanas", tags: ["geo", "ai search", "google ai overview"] },
  { slug: "docker-kubernetes-untuk-deployment-aplikasi", title: "Docker & Kubernetes: Panduan Deployment Aplikasi Modern", description: "Pengenalan containerization dengan Docker dan orchestration dengan Kubernetes untuk deployment yang scalable.", category: "Teknologi", date: "2024-10-20", readTime: "13 menit", author: "Tim Nufanas", tags: ["docker", "kubernetes", "devops"] },
  { slug: "website-rental-mobil-fitur-dan-tips", title: "Website Rental Mobil: Fitur Penting dan Tips Optimasi", description: "Fitur yang wajib ada di website rental mobil: booking system, fleet management, dan strategi SEO lokal.", category: "Website", date: "2024-10-15", readTime: "8 menit", author: "Tim Nufanas", tags: ["website rental", "booking system", "bisnis rental"] },
  { slug: "content-marketing-strategi-untuk-website-bisnis", title: "Content Marketing: Strategi Konten untuk Website Bisnis", description: "Panduan content marketing dari A-Z: riset keyword, content pillar, kalender editorial, dan distribusi konten.", category: "Digital Marketing", date: "2024-10-10", readTime: "12 menit", author: "Tim Nufanas", tags: ["content marketing", "strategi konten", "blog bisnis"] },
  { slug: "aplikasi-sekolah-e-learning-fitur-penting", title: "Aplikasi Sekolah & E-Learning: Fitur Penting untuk Pendidikan Digital", description: "Fitur yang harus ada di aplikasi sekolah dan platform e-learning. LMS, absensi digital, raport online.", category: "Aplikasi", date: "2024-10-05", readTime: "10 menit", author: "Tim Nufanas", tags: ["aplikasi sekolah", "e-learning", "lms"] },
  { slug: "cara-membuat-sitemap-xml-website", title: "Cara Membuat Sitemap XML untuk Website: Panduan SEO", description: "Tutorial membuat dan submit sitemap XML ke Google Search Console. Otomatis dan manual untuk berbagai platform.", category: "Tutorial", date: "2024-10-01", readTime: "6 menit", author: "Tim Nufanas", tags: ["sitemap", "google search console", "technical seo"] },
  { slug: "software-house-bandung-cara-memilih", title: "Software House Bandung: Cara Memilih yang Tepat untuk Project Anda", description: "Tips memilih software house di Bandung. Evaluasi portofolio, teknologi, komunikasi, dan model kerja sama.", category: "Tips", date: "2024-09-25", readTime: "8 menit", author: "Tim Nufanas", tags: ["software house", "vendor software", "outsourcing"] },
];
