export const SITE_CONFIG = {
  name: "Nufanas",
  title: "Nufanas - Digital Agency & Software House Bandung",
  description:
    "Nufanas adalah digital agency dan software house di Bandung yang menyediakan jasa pembuatan website, aplikasi mobile, web application, custom software, AI automation, UI/UX design, SEO, dan digital marketing.",
  url: "https://nufanas.com",
  ogImage: "https://nufanas.com/images/og-image.jpg",
  locale: "id_ID",
  language: "id",
  creator: "Nufanas Digital Agency & Software House",
  keywords: [
    "jasa pembuatan aplikasi bandung",
    "software house bandung",
    "jasa pembuatan website bandung",
    "web developer bandung",
    "mobile app developer bandung",
    "digital agency bandung",
    "jasa seo bandung",
    "custom software bandung",
    "jasa aplikasi android bandung",
    "jasa aplikasi ios bandung",
  ],
} as const;

export const NAP = {
  name: "Nufanas Digital Agency & Software House",
  address: {
    street: "Jl. Cihampelas No. 160",
    city: "Bandung",
    region: "Jawa Barat",
    postalCode: "40131",
    country: "ID",
  },
  phone: "+6282216667733",
  whatsapp: "6282216667733",
  email: "hello@nufanas.com",
  website: "https://nufanas.com",
  geo: {
    latitude: -6.8957,
    longitude: 107.6068,
  },
  openingHours: [
    { day: "Monday", open: "09:00", close: "18:00" },
    { day: "Tuesday", open: "09:00", close: "18:00" },
    { day: "Wednesday", open: "09:00", close: "18:00" },
    { day: "Thursday", open: "09:00", close: "18:00" },
    { day: "Friday", open: "09:00", close: "18:00" },
    { day: "Saturday", open: "09:00", close: "15:00" },
  ],
  socialMedia: {
    instagram: "https://instagram.com/nufanas",
    linkedin: "https://linkedin.com/company/nufanas",
    facebook: "https://facebook.com/nufanas",
    twitter: "https://twitter.com/nufanas",
    youtube: "https://youtube.com/@nufanas",
    github: "https://github.com/nufanas",
  },
} as const;

// ==========================================
// SERVICE CATEGORIES
// ==========================================
export const SERVICE_CATEGORIES = [
  {
    slug: "website-development",
    title: "Website Development",
    shortTitle: "Website",
    description: "Jasa pembuatan website profesional untuk bisnis di Bandung",
    icon: "globe",
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development",
    shortTitle: "Mobile App",
    description: "Jasa pembuatan aplikasi mobile Android & iOS di Bandung",
    icon: "smartphone",
  },
  {
    slug: "web-application",
    title: "Web Application Development",
    shortTitle: "Web App",
    description: "Jasa pembuatan web application dan sistem informasi di Bandung",
    icon: "layoutDashboard",
  },
  {
    slug: "enterprise-software",
    title: "Enterprise Software",
    shortTitle: "Enterprise",
    description: "Jasa pembuatan ERP, CRM, HRIS, dan software enterprise di Bandung",
    icon: "building",
  },
  {
    slug: "custom-software",
    title: "Custom Software Development",
    shortTitle: "Custom Software",
    description: "Jasa pengembangan software custom sesuai kebutuhan bisnis Anda",
    icon: "code",
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX Design",
    shortTitle: "UI/UX Design",
    description: "Jasa desain UI/UX premium untuk website dan aplikasi mobile",
    icon: "palette",
  },
  {
    slug: "seo",
    title: "SEO & Digital Optimization",
    shortTitle: "SEO",
    description: "Jasa SEO dan optimasi digital untuk meningkatkan ranking Google",
    icon: "search",
  },
  {
    slug: "ai-automation",
    title: "AI Automation",
    shortTitle: "AI Automation",
    description: "Jasa implementasi AI dan otomasi bisnis untuk efisiensi operasional",
    icon: "brain",
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    shortTitle: "Digital Marketing",
    description: "Jasa digital marketing, Google Ads, Meta Ads, dan branding",
    icon: "megaphone",
  },
] as const;

// ==========================================
// WEBSITE SERVICES
// ==========================================
export const WEBSITE_SERVICES = [
  {
    slug: "jasa-website-bandung",
    title: "Jasa Website Bandung",
    shortTitle: "Website Bandung",
    description: "Jasa pembuatan website profesional di Bandung dengan desain premium, performa cepat, dan SEO-ready.",
    icon: "globe",
    price: "Mulai Rp 3.500.000",
    category: "website-development",
  },
  {
    slug: "jasa-pembuatan-website-bandung",
    title: "Jasa Pembuatan Website Bandung",
    shortTitle: "Pembuatan Website",
    description: "Layanan pembuatan website custom dari nol untuk bisnis di Bandung. Full responsive dan mobile-first.",
    icon: "code",
    price: "Mulai Rp 5.000.000",
    category: "website-development",
  },
  {
    slug: "web-developer-bandung",
    title: "Web Developer Bandung",
    shortTitle: "Web Developer",
    description: "Tim web developer berpengalaman di Bandung siap membangun website modern dengan teknologi terkini.",
    icon: "terminal",
    price: "Mulai Rp 7.500.000",
    category: "website-development",
  },
  {
    slug: "web-design-bandung",
    title: "Web Design Bandung",
    shortTitle: "Web Design",
    description: "Jasa web design premium di Bandung. UI/UX modern yang meningkatkan conversion rate.",
    icon: "palette",
    price: "Mulai Rp 4.000.000",
    category: "website-development",
  },
  {
    slug: "website-company-profile-bandung",
    title: "Website Company Profile Bandung",
    shortTitle: "Company Profile",
    description: "Jasa pembuatan website company profile profesional di Bandung untuk kredibilitas perusahaan.",
    icon: "building",
    price: "Mulai Rp 3.500.000",
    category: "website-development",
  },
  {
    slug: "website-toko-online-bandung",
    title: "Website Toko Online Bandung",
    shortTitle: "Toko Online",
    description: "Pembuatan website toko online dan e-commerce di Bandung dengan payment gateway.",
    icon: "shoppingCart",
    price: "Mulai Rp 8.000.000",
    category: "website-development",
  },
  {
    slug: "landing-page-bandung",
    title: "Landing Page Bandung",
    shortTitle: "Landing Page",
    description: "Jasa pembuatan landing page high-converting di Bandung untuk lead generation.",
    icon: "mousePointer",
    price: "Mulai Rp 2.500.000",
    category: "website-development",
  },
  {
    slug: "website-umkm-bandung",
    title: "Website UMKM Bandung",
    shortTitle: "Website UMKM",
    description: "Jasa pembuatan website murah untuk UMKM di Bandung. Paket lengkap.",
    icon: "store",
    price: "Mulai Rp 1.500.000",
    category: "website-development",
  },
  {
    slug: "website-sekolah-bandung",
    title: "Website Sekolah Bandung",
    shortTitle: "Website Sekolah",
    description: "Jasa pembuatan website sekolah dan lembaga pendidikan di Bandung.",
    icon: "graduationCap",
    price: "Mulai Rp 3.000.000",
    category: "website-development",
  },
  {
    slug: "website-klinik-bandung",
    title: "Website Klinik Bandung",
    shortTitle: "Website Klinik",
    description: "Pembuatan website klinik dan rumah sakit di Bandung.",
    icon: "heart",
    price: "Mulai Rp 4.500.000",
    category: "website-development",
  },
  {
    slug: "website-cafe-bandung",
    title: "Website Cafe Bandung",
    shortTitle: "Website Cafe",
    description: "Jasa pembuatan website cafe dan restoran di Bandung.",
    icon: "coffee",
    price: "Mulai Rp 3.000.000",
    category: "website-development",
  },
  {
    slug: "website-hotel-bandung",
    title: "Website Hotel Bandung",
    shortTitle: "Website Hotel",
    description: "Pembuatan website hotel dan penginapan di Bandung dengan booking system.",
    icon: "bed",
    price: "Mulai Rp 7.000.000",
    category: "website-development",
  },
  {
    slug: "website-rental-mobil-bandung",
    title: "Website Rental Mobil Bandung",
    shortTitle: "Website Rental",
    description: "Jasa pembuatan website rental mobil di Bandung dengan booking online.",
    icon: "car",
    price: "Mulai Rp 5.000.000",
    category: "website-development",
  },
  {
    slug: "website-travel-bandung",
    title: "Website Travel Bandung",
    shortTitle: "Website Travel",
    description: "Pembuatan website travel dan tour di Bandung.",
    icon: "plane",
    price: "Mulai Rp 6.000.000",
    category: "website-development",
  },
  {
    slug: "website-kontraktor-bandung",
    title: "Website Kontraktor Bandung",
    shortTitle: "Website Kontraktor",
    description: "Jasa pembuatan website kontraktor dan konstruksi di Bandung.",
    icon: "hardHat",
    price: "Mulai Rp 4.000.000",
    category: "website-development",
  },
  {
    slug: "website-properti-bandung",
    title: "Website Properti Bandung",
    shortTitle: "Website Properti",
    description: "Pembuatan website properti dan real estate di Bandung.",
    icon: "home",
    price: "Mulai Rp 8.000.000",
    category: "website-development",
  },
  {
    slug: "website-furniture-bandung",
    title: "Website Furniture Bandung",
    shortTitle: "Website Furniture",
    description: "Jasa pembuatan website furniture dan interior di Bandung.",
    icon: "sofa",
    price: "Mulai Rp 5.000.000",
    category: "website-development",
  },
  {
    slug: "website-industri-bandung",
    title: "Website Industri Bandung",
    shortTitle: "Website Industri",
    description: "Pembuatan website industri dan manufaktur di Bandung.",
    icon: "factory",
    price: "Mulai Rp 6.000.000",
    category: "website-development",
  },
] as const;

// ==========================================
// APP SERVICES
// ==========================================
export const APP_SERVICES = [
  {
    slug: "jasa-pembuatan-aplikasi-bandung",
    title: "Jasa Pembuatan Aplikasi Bandung",
    shortTitle: "Aplikasi Bandung",
    description: "Jasa pembuatan aplikasi mobile dan web application profesional di Bandung untuk bisnis Anda.",
    icon: "smartphone",
    price: "Mulai Rp 15.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-android-bandung",
    title: "Jasa Pembuatan Aplikasi Android Bandung",
    shortTitle: "Aplikasi Android",
    description: "Jasa pembuatan aplikasi Android native dan cross-platform di Bandung dengan Flutter & Kotlin.",
    icon: "smartphone",
    price: "Mulai Rp 20.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-ios-bandung",
    title: "Jasa Pembuatan Aplikasi iOS Bandung",
    shortTitle: "Aplikasi iOS",
    description: "Jasa pembuatan aplikasi iPhone dan iPad di Bandung dengan Swift dan Flutter.",
    icon: "smartphone",
    price: "Mulai Rp 25.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-mobile-bandung",
    title: "Jasa Pembuatan Aplikasi Mobile Bandung",
    shortTitle: "Aplikasi Mobile",
    description: "Jasa pembuatan aplikasi mobile cross-platform di Bandung. Satu codebase untuk Android & iOS.",
    icon: "smartphone",
    price: "Mulai Rp 25.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-web-application-bandung",
    title: "Jasa Pembuatan Web Application Bandung",
    shortTitle: "Web Application",
    description: "Jasa pembuatan web application dan sistem berbasis web di Bandung untuk otomasi bisnis.",
    icon: "layoutDashboard",
    price: "Mulai Rp 20.000.000",
    category: "web-application",
  },
  {
    slug: "jasa-custom-software-bandung",
    title: "Jasa Custom Software Development Bandung",
    shortTitle: "Custom Software",
    description: "Jasa pengembangan software custom sesuai kebutuhan unik bisnis Anda di Bandung.",
    icon: "code",
    price: "Mulai Rp 30.000.000",
    category: "custom-software",
  },
  {
    slug: "jasa-sistem-informasi-bandung",
    title: "Jasa Pembuatan Sistem Informasi Bandung",
    shortTitle: "Sistem Informasi",
    description: "Jasa pembuatan sistem informasi manajemen terintegrasi di Bandung untuk efisiensi bisnis.",
    icon: "database",
    price: "Mulai Rp 25.000.000",
    category: "enterprise-software",
  },
  {
    slug: "jasa-erp-bandung",
    title: "Jasa Pembuatan ERP Bandung",
    shortTitle: "ERP System",
    description: "Jasa pembuatan sistem ERP (Enterprise Resource Planning) di Bandung untuk manajemen bisnis terpadu.",
    icon: "building",
    price: "Mulai Rp 50.000.000",
    category: "enterprise-software",
  },
  {
    slug: "jasa-crm-bandung",
    title: "Jasa Pembuatan CRM Bandung",
    shortTitle: "CRM System",
    description: "Jasa pembuatan sistem CRM (Customer Relationship Management) di Bandung.",
    icon: "users",
    price: "Mulai Rp 30.000.000",
    category: "enterprise-software",
  },
  {
    slug: "jasa-hris-bandung",
    title: "Jasa Pembuatan HRIS Bandung",
    shortTitle: "HRIS System",
    description: "Jasa pembuatan sistem HRIS (Human Resource Information System) di Bandung untuk manajemen SDM.",
    icon: "userCog",
    price: "Mulai Rp 35.000.000",
    category: "enterprise-software",
  },
  {
    slug: "jasa-pos-bandung",
    title: "Jasa Pembuatan POS Bandung",
    shortTitle: "POS System",
    description: "Jasa pembuatan sistem POS (Point of Sale) di Bandung untuk retail dan F&B.",
    icon: "creditCard",
    price: "Mulai Rp 15.000.000",
    category: "enterprise-software",
  },
  {
    slug: "jasa-aplikasi-kasir-bandung",
    title: "Jasa Pembuatan Aplikasi Kasir Bandung",
    shortTitle: "Aplikasi Kasir",
    description: "Jasa pembuatan aplikasi kasir digital di Bandung untuk toko, cafe, dan restoran.",
    icon: "calculator",
    price: "Mulai Rp 10.000.000",
    category: "enterprise-software",
  },
  {
    slug: "jasa-aplikasi-inventory-bandung",
    title: "Jasa Pembuatan Aplikasi Inventory Bandung",
    shortTitle: "Aplikasi Inventory",
    description: "Jasa pembuatan aplikasi manajemen inventory dan gudang di Bandung.",
    icon: "package",
    price: "Mulai Rp 20.000.000",
    category: "enterprise-software",
  },
  {
    slug: "jasa-aplikasi-klinik-bandung",
    title: "Jasa Pembuatan Aplikasi Klinik Bandung",
    shortTitle: "Aplikasi Klinik",
    description: "Jasa pembuatan aplikasi manajemen klinik dan rekam medis di Bandung.",
    icon: "heart",
    price: "Mulai Rp 35.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-rumah-sakit-bandung",
    title: "Jasa Pembuatan Aplikasi Rumah Sakit Bandung",
    shortTitle: "Aplikasi RS",
    description: "Jasa pembuatan sistem informasi rumah sakit (SIMRS) di Bandung.",
    icon: "hospital",
    price: "Mulai Rp 75.000.000",
    category: "enterprise-software",
  },
  {
    slug: "jasa-aplikasi-sekolah-bandung",
    title: "Jasa Pembuatan Aplikasi Sekolah Bandung",
    shortTitle: "Aplikasi Sekolah",
    description: "Jasa pembuatan aplikasi manajemen sekolah dan e-learning di Bandung.",
    icon: "graduationCap",
    price: "Mulai Rp 25.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-hotel-bandung",
    title: "Jasa Pembuatan Aplikasi Hotel Bandung",
    shortTitle: "Aplikasi Hotel",
    description: "Jasa pembuatan aplikasi manajemen hotel dan booking system di Bandung.",
    icon: "bed",
    price: "Mulai Rp 40.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-cafe-bandung",
    title: "Jasa Pembuatan Aplikasi Cafe Bandung",
    shortTitle: "Aplikasi Cafe",
    description: "Jasa pembuatan aplikasi order dan manajemen cafe di Bandung.",
    icon: "coffee",
    price: "Mulai Rp 20.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-restoran-bandung",
    title: "Jasa Pembuatan Aplikasi Restoran Bandung",
    shortTitle: "Aplikasi Restoran",
    description: "Jasa pembuatan aplikasi manajemen restoran dan delivery di Bandung.",
    icon: "utensils",
    price: "Mulai Rp 25.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-rental-mobil-bandung",
    title: "Jasa Pembuatan Aplikasi Rental Mobil Bandung",
    shortTitle: "Aplikasi Rental",
    description: "Jasa pembuatan aplikasi booking rental mobil di Bandung.",
    icon: "car",
    price: "Mulai Rp 30.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-travel-bandung",
    title: "Jasa Pembuatan Aplikasi Travel Bandung",
    shortTitle: "Aplikasi Travel",
    description: "Jasa pembuatan aplikasi travel dan booking wisata di Bandung.",
    icon: "plane",
    price: "Mulai Rp 35.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-aplikasi-properti-bandung",
    title: "Jasa Pembuatan Aplikasi Properti Bandung",
    shortTitle: "Aplikasi Properti",
    description: "Jasa pembuatan aplikasi listing properti dan real estate di Bandung.",
    icon: "home",
    price: "Mulai Rp 35.000.000",
    category: "mobile-app-development",
  },
  {
    slug: "jasa-marketplace-bandung",
    title: "Jasa Pembuatan Marketplace Bandung",
    shortTitle: "Marketplace",
    description: "Jasa pembuatan platform marketplace multi-vendor di Bandung.",
    icon: "store",
    price: "Mulai Rp 75.000.000",
    category: "web-application",
  },
  {
    slug: "jasa-saas-bandung",
    title: "Jasa Pembuatan SaaS Bandung",
    shortTitle: "SaaS Platform",
    description: "Jasa pembuatan produk SaaS (Software as a Service) di Bandung.",
    icon: "cloud",
    price: "Mulai Rp 100.000.000",
    category: "web-application",
  },
  {
    slug: "jasa-dashboard-bandung",
    title: "Jasa Pembuatan Dashboard Bandung",
    shortTitle: "Dashboard",
    description: "Jasa pembuatan dashboard analytics dan business intelligence di Bandung.",
    icon: "barChart",
    price: "Mulai Rp 20.000.000",
    category: "web-application",
  },
  {
    slug: "jasa-aplikasi-ai-bandung",
    title: "Jasa Pembuatan Aplikasi AI Bandung",
    shortTitle: "Aplikasi AI",
    description: "Jasa pembuatan aplikasi berbasis AI dan machine learning di Bandung.",
    icon: "brain",
    price: "Mulai Rp 50.000.000",
    category: "ai-automation",
  },
] as const;

// Combined all services
export const ALL_SERVICES = [...WEBSITE_SERVICES, ...APP_SERVICES] as const;

// SEO service
export const SEO_SERVICE = {
  slug: "jasa-seo-bandung",
  title: "Jasa SEO Bandung",
  shortTitle: "SEO Bandung",
  description: "Layanan SEO profesional di Bandung untuk meningkatkan ranking website di Google.",
  icon: "search",
  price: "Mulai Rp 3.000.000/bulan",
  category: "seo",
} as const;

export const ENTITIES = {
  areas: [
    "Bandung", "Kota Bandung", "Jawa Barat", "Cimahi", "Lembang",
    "Soreang", "Rancaekek", "Cileunyi", "Dayeuhkolot", "Majalaya",
    "Buah Batu", "Antapani", "Setiabudi", "Pasteur", "Dago",
    "Ujung Berung", "Lengkong", "Batununggal", "Kopo", "Cibiru",
  ],
} as const;

export const NAVIGATION = {
  main: [
    { label: "Beranda", href: "/" },
    { label: "Layanan", href: "/layanan" },
    { label: "Portfolio", href: "/portfolio" },
    { label: "Harga", href: "/harga" },
    { label: "Blog", href: "/blog" },
    { label: "Tentang", href: "/tentang" },
    { label: "Kontak", href: "/kontak" },
  ],
  services: [
    { label: "Website Development", href: "/layanan/jasa-website-bandung" },
    { label: "Mobile App Development", href: "/layanan/jasa-pembuatan-aplikasi-bandung" },
    { label: "Web Application", href: "/layanan/jasa-web-application-bandung" },
    { label: "Enterprise Software (ERP/CRM)", href: "/layanan/jasa-erp-bandung" },
    { label: "Custom Software", href: "/layanan/jasa-custom-software-bandung" },
    { label: "UI/UX Design", href: "/layanan/web-design-bandung" },
    { label: "SEO", href: "/layanan/jasa-seo-bandung" },
    { label: "AI Automation", href: "/layanan/jasa-aplikasi-ai-bandung" },
  ],
} as const;

export const TECHNOLOGIES = [
  { name: "Flutter", category: "Mobile", slug: "flutter" },
  { name: "React Native", category: "Mobile", slug: "react-native" },
  { name: "Kotlin", category: "Mobile", slug: "kotlin" },
  { name: "Swift", category: "Mobile", slug: "swift" },
  { name: "Next.js", category: "Frontend", slug: "nextjs" },
  { name: "React", category: "Frontend", slug: "react" },
  { name: "Node.js", category: "Backend", slug: "nodejs" },
  { name: "NestJS", category: "Backend", slug: "nestjs" },
  { name: "Laravel", category: "Backend", slug: "laravel" },
  { name: "Python", category: "Backend", slug: "python" },
  { name: "Go", category: "Backend", slug: "go" },
  { name: "Java", category: "Backend", slug: "java" },
  { name: "PostgreSQL", category: "Database", slug: "postgresql" },
  { name: "MySQL", category: "Database", slug: "mysql" },
  { name: "MongoDB", category: "Database", slug: "mongodb" },
  { name: "Redis", category: "Cache", slug: "redis" },
  { name: "Docker", category: "DevOps", slug: "docker" },
  { name: "Kubernetes", category: "DevOps", slug: "kubernetes" },
  { name: "AWS", category: "Cloud", slug: "aws" },
  { name: "Google Cloud", category: "Cloud", slug: "google-cloud" },
  { name: "Vercel", category: "Hosting", slug: "vercel" },
  { name: "Supabase", category: "BaaS", slug: "supabase" },
  { name: "Firebase", category: "BaaS", slug: "firebase" },
  { name: "Prisma", category: "ORM", slug: "prisma" },
] as const;
